salle1:
   roomType: #String
   camera:
      location: #Location
      rotation: #Rotation
   animPose:
      Bonnie: 
         pos1:
            location:
            rotation:
            head:
            leftArm:
            rightArm:
            body:
            leftLeg:
            rightLeg:
      Freddy:
      Chica:
      Foxy:
      Mangle:
      Springtrap:
      